const styles = {
  page: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    maxWidth: '1600px',
    margin: '0 auto',
  },

  // Header Bar
  headerBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '16px',
    paddingBottom: '4px',
  },
  headerTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    flexWrap: 'wrap',
  },
  headerTitle: {
    margin: 0,
    fontSize: '24px',
    fontWeight: '700',
    color: '#0f172a',
    letterSpacing: '-0.5px',
  },
  headerSubtitle: {
    margin: '4px 0 0 0',
    fontSize: '14px',
    color: '#64748b',
  },
  livePill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: '#ecfdf5',
    border: '1px solid #a7f3d0',
    padding: '4px 10px',
    borderRadius: '9999px',
  },
  liveDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    backgroundColor: '#10b981',
  },
  liveDotSmall: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    backgroundColor: '#ef4444',
  },
  liveText: {
    fontSize: '12px',
    fontWeight: '600',
    color: '#047857',
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  lastUpdateText: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    color: '#64748b',
    backgroundColor: '#ffffff',
    padding: '8px 12px',
    borderRadius: '8px',
    border: '1px solid #e2e8f0',
  },
  refreshBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '8px 16px',
    backgroundColor: '#ffffff',
    color: '#2563eb',
    border: '1px solid #bfdbfe',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },

  // Alert Banners
  dangerAlertBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    backgroundColor: '#fef2f2',
    border: '1px solid #fecaca',
    borderRadius: '12px',
    padding: '16px 20px',
    boxShadow: '0 4px 6px -1px rgba(220, 38, 38, 0.08)',
    flexWrap: 'wrap',
  },
  alertBannerIconWrapperDanger: {
    width: '44px',
    height: '44px',
    borderRadius: '10px',
    backgroundColor: '#fee2e2',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  alertTitleDanger: {
    fontSize: '15px',
    fontWeight: '700',
    color: '#991b1b',
  },
  alertSubtitleDanger: {
    fontSize: '13px',
    color: '#b91c1c',
    marginTop: '2px',
  },
  alertActionBtnDanger: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '8px 14px',
    backgroundColor: '#dc2626',
    color: '#ffffff',
    border: 'none',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
  },

  safeAlertBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    backgroundColor: '#f0fdf4',
    border: '1px solid #bbf7d0',
    borderRadius: '12px',
    padding: '14px 20px',
    flexWrap: 'wrap',
  },
  alertBannerIconWrapperSafe: {
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    backgroundColor: '#dcfce7',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  alertTitleSafe: {
    fontSize: '14px',
    fontWeight: '700',
    color: '#166534',
  },
  alertSubtitleSafe: {
    fontSize: '13px',
    color: '#15803d',
    marginTop: '2px',
  },
  safeBadgePill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: '#dcfce7',
    padding: '6px 12px',
    borderRadius: '9999px',
    fontSize: '12px',
    fontWeight: '600',
    color: '#166534',
  },

  // 4 Stat Cards
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: '16px',
  },
  statCard: {
    backgroundColor: '#ffffff',
    borderRadius: '14px',
    padding: '20px',
    border: '1px solid #e2e8f0',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  statCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  statCardTitle: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#64748b',
  },
  statIconBadge: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statCardValue: {
    fontSize: '30px',
    fontWeight: '700',
    color: '#0f172a',
    marginTop: '10px',
    letterSpacing: '-0.5px',
  },
  statCardFooter: {
    marginTop: '12px',
    fontSize: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  progressContainer: {
    width: '100%',
    height: '6px',
    backgroundColor: '#f1f5f9',
    borderRadius: '9999px',
    overflow: 'hidden',
    marginTop: '10px',
  },
  progressBar: {
    height: '100%',
    borderRadius: '9999px',
    transition: 'width 0.4s ease-in-out',
  },
  statCardSubText: {
    fontSize: '12px',
    color: '#64748b',
    marginTop: '8px',
  },
  detectionPillsRow: {
    display: 'flex',
    gap: '8px',
    marginTop: '10px',
  },
  miniFirePill: {
    fontSize: '11px',
    fontWeight: '600',
    color: '#b91c1c',
    backgroundColor: '#fee2e2',
    padding: '2px 8px',
    borderRadius: '6px',
  },
  miniSmokePill: {
    fontSize: '11px',
    fontWeight: '600',
    color: '#b45309',
    backgroundColor: '#fef3c7',
    padding: '2px 8px',
    borderRadius: '6px',
  },

  // Main Split Grid
  splitGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.65fr) minmax(0, 1fr)',
    gap: '24px',
    alignItems: 'start',
  },

  // Left Column Card
  mainCard: {
    backgroundColor: '#ffffff',
    borderRadius: '14px',
    border: '1px solid #e2e8f0',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
    overflow: 'hidden',
  },
  cardHeaderArea: {
    padding: '18px 24px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid #f1f5f9',
    flexWrap: 'wrap',
    gap: '12px',
  },
  cardHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  cardTitleWithIcon: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  cardTitle: {
    margin: 0,
    fontSize: '16px',
    fontWeight: '700',
    color: '#0f172a',
  },
  badgeLivePulse: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    backgroundColor: '#fee2e2',
    color: '#dc2626',
    fontSize: '11px',
    fontWeight: '700',
    padding: '3px 8px',
    borderRadius: '9999px',
    textTransform: 'uppercase',
  },
  filterGroup: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    padding: '3px',
    borderRadius: '8px',
    gap: '2px',
  },
  filterTab: {
    padding: '5px 12px',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: '500',
    color: '#64748b',
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
  },
  filterTabActive: {
    backgroundColor: '#ffffff',
    color: '#0f172a',
    fontWeight: '600',
    boxShadow: '0 1px 2px rgba(0,0,0,0.06)',
  },
  filterTabActiveFire: {
    backgroundColor: '#dc2626',
    color: '#ffffff',
    fontWeight: '600',
    boxShadow: '0 1px 2px rgba(220, 38, 38, 0.2)',
  },
  filterTabActiveSmoke: {
    backgroundColor: '#d97706',
    color: '#ffffff',
    fontWeight: '600',
    boxShadow: '0 1px 2px rgba(217, 119, 6, 0.2)',
  },

  // Table
  tableScroll: {
    overflowX: 'auto',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'left',
    fontSize: '13px',
  },
  tableHeadRow: {
    backgroundColor: '#f8fafc',
    borderBottom: '1px solid #e2e8f0',
    color: '#475569',
  },
  th: {
    padding: '12px 14px',
    fontSize: '12px',
    fontWeight: '600',
    whiteSpace: 'nowrap',
  },
  tableRow: {
    borderBottom: '1px solid #f1f5f9',
    transition: 'background-color 0.15s',
  },
  td: {
    padding: '12px 14px',
    verticalAlign: 'middle',
  },

  eventIdText: {
    fontWeight: '600',
    color: '#0f172a',
    fontFamily: 'monospace',
    fontSize: '13px',
  },
  subTextMuted: {
    fontSize: '11px',
    color: '#94a3b8',
    marginTop: '2px',
  },

  // Multi-type badges container
  typeBadgesContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    alignItems: 'flex-start',
  },
  typeBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    padding: '3px 9px',
    borderRadius: '9999px',
    fontSize: '11px',
    fontWeight: '700',
    letterSpacing: '0.3px',
    whiteSpace: 'nowrap',
  },

  // Confidence cells list
  confColumnList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    width: '95px',
  },
  confCell: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
  },
  confRowHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '11px',
  },
  confLabelType: {
    fontSize: '10px',
    color: '#64748b',
    fontWeight: '600',
  },
  confValueText: {
    fontSize: '11px',
    fontWeight: '700',
    color: '#0f172a',
  },
  confBarBg: {
    width: '100%',
    height: '4px',
    backgroundColor: '#e2e8f0',
    borderRadius: '2px',
    overflow: 'hidden',
  },
  confBarFill: {
    height: '100%',
    borderRadius: '2px',
  },

  locationBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  cameraName: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  camMonoId: {
    fontFamily: 'monospace',
    fontWeight: '600',
    color: '#334155',
    fontSize: '12px',
  },
  camLocationText: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '12px',
    color: '#64748b',
  },
  timeMain: {
    fontWeight: '500',
    color: '#1e293b',
    fontSize: '13px',
  },
  viewDetailsBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    padding: '6px 12px',
    backgroundColor: '#f1f5f9',
    color: '#1e293b',
    border: '1px solid #e2e8f0',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.15s',
  },

  // Card Footer
  cardFooter: {
    padding: '14px 24px',
    backgroundColor: '#f8fafc',
    borderTop: '1px solid #f1f5f9',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '13px',
  },
  cardFooterNote: {
    color: '#64748b',
    fontSize: '12px',
  },
  footerLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    color: '#2563eb',
    fontWeight: '600',
    textDecoration: 'none',
  },

  // Right Column
  rightColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  sideCard: {
    backgroundColor: '#ffffff',
    borderRadius: '14px',
    border: '1px solid #e2e8f0',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
    overflow: 'hidden',
  },
  sideCardHeader: {
    padding: '18px 20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid #f1f5f9',
  },
  sideCardTitle: {
    margin: 0,
    fontSize: '15px',
    fontWeight: '700',
    color: '#0f172a',
  },
  smallManageLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '3px',
    fontSize: '12px',
    fontWeight: '600',
    color: '#2563eb',
    textDecoration: 'none',
  },
  analyticsBody: {
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  ratioHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  subLabel: {
    fontSize: '13px',
    color: '#64748b',
    fontWeight: '500',
  },
  subValue: {
    fontSize: '12px',
    color: '#0f172a',
    fontWeight: '600',
  },
  stackedBar: {
    width: '100%',
    height: '10px',
    backgroundColor: '#f1f5f9',
    borderRadius: '9999px',
    display: 'flex',
    overflow: 'hidden',
  },
  stackedBarEmpty: {
    width: '100%',
    height: '10px',
    backgroundColor: '#f1f5f9',
    borderRadius: '9999px',
  },
  barSegmentFire: {
    height: '100%',
    backgroundColor: '#ef4444',
    transition: 'width 0.4s ease',
  },
  barSegmentSmoke: {
    height: '100%',
    backgroundColor: '#f59e0b',
    transition: 'width 0.4s ease',
  },
  legendGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
  },
  legendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    backgroundColor: '#f8fafc',
    padding: '10px 12px',
    borderRadius: '8px',
    border: '1px solid #f1f5f9',
  },
  legendIndicatorFire: {
    width: '10px',
    height: '10px',
    borderRadius: '3px',
    backgroundColor: '#ef4444',
    flexShrink: 0,
  },
  legendIndicatorSmoke: {
    width: '10px',
    height: '10px',
    borderRadius: '3px',
    backgroundColor: '#f59e0b',
    flexShrink: 0,
  },
  legendLabel: {
    fontSize: '11px',
    color: '#64748b',
    fontWeight: '500',
  },
  legendNum: {
    fontSize: '14px',
    fontWeight: '700',
    color: '#0f172a',
  },
  legendPct: {
    fontSize: '11px',
    fontWeight: '500',
    color: '#64748b',
  },
  confidenceMetricBox: {
    backgroundColor: '#f8fafc',
    padding: '12px 14px',
    borderRadius: '8px',
    border: '1px solid #e2e8f0',
  },

  // Camera List
  cameraListScroll: {
    maxHeight: '340px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
  },
  camListItem: {
    padding: '12px 20px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid #f1f5f9',
  },
  camItemLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  camStatusDot: {
    width: '9px',
    height: '9px',
    borderRadius: '50%',
    flexShrink: 0,
  },
  camItemName: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
    fontWeight: '600',
    color: '#0f172a',
    fontFamily: 'monospace',
  },
  camIpTag: {
    fontSize: '11px',
    color: '#64748b',
    fontWeight: '400',
  },
  camItemLocation: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '11px',
    color: '#64748b',
    marginTop: '2px',
  },
  camMiniBadge: {
    fontSize: '11px',
    fontWeight: '600',
    padding: '3px 8px',
    borderRadius: '9999px',
  },

  // Empty & Loading states
  loadingArea: {
    padding: '50px 20px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyArea: {
    padding: '50px 20px',
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  emptyIconCircle: {
    width: '56px',
    height: '56px',
    borderRadius: '50%',
    backgroundColor: '#f0fdf4',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '12px',
  },
  emptyTitle: {
    margin: '0 0 6px 0',
    fontSize: '15px',
    fontWeight: '600',
    color: '#1e293b',
  },
  emptyDesc: {
    margin: 0,
    fontSize: '13px',
    color: '#64748b',
    maxWidth: '380px',
    lineHeight: '1.5',
  },
  sideEmpty: {
    padding: '36px 20px',
    textAlign: 'center',
  },

  // Modal Styles
  modalBackdrop: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.65)',
    backdropFilter: 'blur(3px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1050,
    padding: '20px',
  },
  modalContainer: {
    width: '100%',
    maxWidth: '680px',
    backgroundColor: '#ffffff',
    borderRadius: '16px',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    maxHeight: '90vh',
  },
  modalHeader: {
    padding: '18px 24px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid #e2e8f0',
    backgroundColor: '#f8fafc',
  },
  modalHeaderTitleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  modalTitle: {
    margin: 0,
    fontSize: '16px',
    fontWeight: '700',
    color: '#0f172a',
  },
  modalSubtitle: {
    fontSize: '12px',
    color: '#64748b',
    marginTop: '2px',
  },
  modalCloseBtn: {
    width: '32px',
    height: '32px',
    borderRadius: '8px',
    border: '1px solid #cbd5e1',
    backgroundColor: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    color: '#475569',
  },
  modalBody: {
    padding: '24px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  modalImageContainer: {
    width: '100%',
    height: '320px',
    minHeight: '320px',
    maxHeight: '320px',
    borderRadius: '12px',
    backgroundColor: '#0f172a',
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1px solid #e2e8f0',
    flexShrink: 0,
  },
  modalImage: {
    width: '100%',
    height: '100%',
    objectFit: 'contain',
  },
  modalImageFallback: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f1f5f9',
    width: '100%',
    height: '100%',
  },
  modalDetailsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '12px',
  },
  modalDetailCard: {
    backgroundColor: '#f8fafc',
    padding: '12px 16px',
    borderRadius: '10px',
    border: '1px solid #e2e8f0',
  },
  modalDetailLabel: {
    fontSize: '11px',
    fontWeight: '600',
    color: '#64748b',
    textTransform: 'uppercase',
  },
  modalDetailValue: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#0f172a',
    marginTop: '4px',
  },
  modalDetailValueMono: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#0f172a',
    fontFamily: 'monospace',
    marginTop: '4px',
  },
  modalDetailSub: {
    fontSize: '12px',
    color: '#64748b',
    marginTop: '2px',
  },
  bboxSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  bboxSectionTitle: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#334155',
  },
  bboxGridScroll: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    maxHeight: '180px',
    overflowY: 'auto',
    paddingRight: '4px',
  },
  bboxItem: {
    backgroundColor: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    padding: '10px 14px',
    fontSize: '12px',
  },
  bboxItemTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '4px',
  },
  bboxCoords: {
    color: '#64748b',
    fontFamily: 'monospace',
    fontSize: '11px',
  },
  modalFooter: {
    padding: '16px 24px',
    borderTop: '1px solid #e2e8f0',
    backgroundColor: '#f8fafc',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalFullHistoryBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    color: '#2563eb',
    fontSize: '13px',
    fontWeight: '600',
    textDecoration: 'none',
  },
  modalDismissBtn: {
    padding: '8px 18px',
    backgroundColor: '#0f172a',
    color: '#ffffff',
    border: 'none',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
  },
};

export default styles;
