const S = {
  container: {
    display: 'flex',
    minHeight: '100vh',
    backgroundColor: '#f8fafc',
    fontFamily: "'Inter', -apple-system, sans-serif",
  },
  sidebar: {
    width: '260px',
    backgroundColor: '#0b1329',
    color: '#ffffff',
    display: 'flex',
    flexDirection: 'column',
    padding: '24px 16px',
    boxSizing: 'border-box',
    flexShrink: 0,
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '32px',
    paddingLeft: '6px',
  },
  logoContainer: {
    width: '36px',
    height: '36px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoImage: {
    width: '36px',
    height: '36px',
    objectFit: 'contain',
  },
  logoFallback: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    backgroundColor: 'rgba(249, 115, 22, 0.15)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandTitle: {
    fontSize: '14px',
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: '0.5px',
  },
  brandSubtitle: {
    fontSize: '9px',
    color: '#94a3b8',
    fontWeight: '600',
    letterSpacing: '0.3px',
  },
  nav: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    flex: 1,
  },
  navSectionHeader: {
    fontSize: '10px',
    fontWeight: '700',
    color: '#64748b',
    letterSpacing: '1px',
    padding: '6px 12px',
    marginBottom: '4px',
  },
  menuItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '11px 14px',
    borderRadius: '10px',
    color: '#94a3b8',
    textDecoration: 'none',
    fontSize: '13px',
    fontWeight: '500',
  },
  activeMenuItem: {
    backgroundColor: '#2563eb',
    color: '#ffffff',
    fontWeight: '600',
    boxShadow: '0 4px 6px -1px rgba(37, 99, 235, 0.25)',
  },
  sidebarFooter: {
    marginTop: 'auto',
    paddingTop: '16px',
    borderTop: '1px solid rgba(255, 255, 255, 0.08)',
  },
  systemStatusBox: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: '8px',
    padding: '10px 12px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  systemStatusTop: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    width: '100%',
  },
  statusDot: {
    width: '7px',
    height: '7px',
    borderRadius: '50%',
    backgroundColor: '#10b981',
  },
  statusLabel: {
    fontSize: '10px',
    fontWeight: '700',
    color: '#10b981',
    letterSpacing: '0.5px',
    lineHeight: '1',
  },
  statusSub: {
    fontSize: '10px',
    color: '#64748b',
    marginTop: '2px',
    paddingLeft: '15px',
    lineHeight: '1',
  },
  mainContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
  },
  header: {
    height: '70px',
    backgroundColor: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 36px',
    borderBottom: '1px solid #e2e8f0',
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  headerCategory: {
    fontSize: '13px',
    color: '#94a3b8',
    fontWeight: '500',
  },
  headerDivider: {
    fontSize: '13px',
    color: '#cbd5e1',
  },
  headerPageName: {
    fontSize: '14px',
    color: '#1e293b',
    fontWeight: '600',
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
  },
  adminDropdownBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    background: '#ffffff',
    border: '1px solid #e2e8f0',
    cursor: 'pointer',
    padding: '6px 12px',
    borderRadius: '10px',
    transition: 'all 0.15s',
  },
  smallAvatar: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    backgroundColor: '#eff6ff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    border: '1px solid #bfdbfe',
  },
  avatarImage: {
    width: '20px',
    height: '20px',
    objectFit: 'contain',
  },
  avatarFallback: {
    display: 'none',
    alignItems: 'center',
    justifyContent: 'center',
  },
  userInfoCol: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '2px',
  },
  usernameText: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#0f172a',
    lineHeight: '1.2',
  },
  roleBadgeMini: {
    fontSize: '9px',
    fontWeight: '700',
    padding: '1px 5px',
    borderRadius: '4px',
    letterSpacing: '0.3px',
  },
  profileModal: {
    position: 'absolute',
    top: '52px',
    right: '0',
    width: '230px',
    backgroundColor: '#ffffff',
    borderRadius: '14px',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)',
    border: '1px solid #e2e8f0',
    padding: '16px',
    zIndex: 1000,
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
  },
  largeAvatar: {
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    backgroundColor: '#eff6ff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1px solid #bfdbfe',
    flexShrink: 0,
  },
  roleBadge: {
    display: 'inline-block',
    padding: '2px 8px',
    borderRadius: '4px',
    fontSize: '10px',
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  bellBtn: {
    position: 'relative',
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    border: '1px solid #e2e8f0',
    backgroundColor: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  bellBadge: {
    position: 'absolute',
    top: '-4px',
    right: '-4px',
    backgroundColor: '#ef4444',
    color: '#ffffff',
    fontSize: '10px',
    fontWeight: '700',
    minWidth: '18px',
    height: '18px',
    borderRadius: '9999px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0 4px',
    boxShadow: '0 2px 4px rgba(239, 68, 68, 0.4)',
    border: '2px solid #ffffff',
    lineHeight: '1',
  },
  notifPopover: {
    position: 'absolute',
    top: '52px',
    right: '0',
    width: '360px',
    backgroundColor: '#ffffff',
    borderRadius: '16px',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)',
    border: '1px solid #e2e8f0',
    overflow: 'hidden',
    zIndex: 1000,
  },
  notifHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 18px',
    borderBottom: '1px solid #f1f5f9',
    backgroundColor: '#ffffff',
  },
  notifCountPill: {
    backgroundColor: '#fef2f2',
    color: '#dc2626',
    fontSize: '11px',
    fontWeight: '700',
    padding: '2px 8px',
    borderRadius: '9999px',
    border: '1px solid #fecaca',
  },
  markAllReadBtn: {
    background: 'none',
    border: 'none',
    color: '#2563eb',
    fontSize: '12px',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '4px 8px',
    borderRadius: '6px',
    transition: 'background 0.15s',
  },
  soundBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 18px',
    backgroundColor: '#f8fafc',
    borderBottom: '1px solid #f1f5f9',
  },
  soundToggleBtn: {
    border: 'none',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: '700',
    padding: '3px 8px',
    cursor: 'pointer',
    transition: 'all 0.15s',
  },
  notifList: {
    maxHeight: '340px',
    overflowY: 'auto',
    padding: '6px 0',
  },
  notifEmpty: {
    padding: '36px 16px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notifItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
    padding: '12px 18px',
    borderBottom: '1px solid #f8fafc',
    cursor: 'pointer',
    transition: 'background 0.15s',
  },
  notifIconWrap: {
    width: '32px',
    height: '32px',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    marginTop: '2px',
  },
  notifItemTop: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
    marginBottom: '2px',
  },
  notifItemTitle: {
    fontSize: '13px',
    fontWeight: '700',
    color: '#0f172a',
  },
  notifItemTime: {
    fontSize: '11px',
    color: '#94a3b8',
    fontWeight: '500',
    whiteSpace: 'nowrap',
  },
  notifItemSub: {
    fontSize: '12px',
    color: '#64748b',
    lineHeight: '1.4',
  },
  notifFooter: {
    padding: '10px 18px',
    borderTop: '1px solid #f1f5f9',
    backgroundColor: '#f8fafc',
    textAlign: 'center',
  },
  viewAllLink: {
    fontSize: '12px',
    fontWeight: '600',
    color: '#2563eb',
    textDecoration: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
  },
  body: {
    padding: '32px 36px',
    flex: 1,
  },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2000,
    backdropFilter: 'blur(3px)',
  },
  closeModalBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#94a3b8',
    fontSize: '18px',
    lineHeight: '1',
    padding: '4px 8px',
    borderRadius: '6px',
    transition: 'all 0.15s',
  },
  infoModal: {
    backgroundColor: '#ffffff',
    borderRadius: '16px',
    padding: '28px',
    width: '420px',
    maxWidth: '92vw',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
  },
  infoIconWrap: {
    width: '42px',
    height: '42px',
    borderRadius: '12px',
    backgroundColor: '#eff6ff',
    border: '1px solid #bfdbfe',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  infoList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    backgroundColor: '#f8fafc',
    borderRadius: '12px',
    padding: '16px 18px',
    border: '1px solid #e2e8f0',
  },
  infoRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: '12px',
    borderBottom: '1px solid #edf2f7',
  },
  infoLabelCol: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
    fontWeight: '600',
    color: '#475569',
  },
  infoValueText: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#0f172a',
  },
  infoCloseBtn: {
    padding: '9px 24px',
    backgroundColor: '#2563eb',
    color: '#ffffff',
    border: 'none',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.15s',
  },
  changePwModal: {
    backgroundColor: '#ffffff',
    borderRadius: '16px',
    padding: '28px',
    width: '410px',
    maxWidth: '92vw',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
  },
  changePwIconWrap: {
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    backgroundColor: '#eff6ff',
    border: '1px solid #bfdbfe',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  changePwField: {
    marginBottom: '14px',
  },
  changePwLabel: {
    display: 'block',
    fontSize: '13px',
    fontWeight: '600',
    color: '#334155',
    marginBottom: '6px',
  },
  changePwInput: {
    width: '100%',
    padding: '11px 14px',
    fontSize: '14px',
    borderRadius: '9px',
    border: '1px solid #cbd5e1',
    outline: 'none',
    boxSizing: 'border-box',
    color: '#0f172a',
    backgroundColor: '#fff',
    transition: 'border-color 0.2s',
  },
  changePwErrorBox: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 14px',
    backgroundColor: '#fef2f2',
    border: '1px solid #fecaca',
    color: '#dc2626',
    borderRadius: '9px',
    fontSize: '13px',
    fontWeight: '500',
    marginBottom: '16px',
  },
  changePwSuccessBox: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 14px',
    backgroundColor: '#f0fdf4',
    border: '1px solid #bbf7d0',
    color: '#16a34a',
    borderRadius: '9px',
    fontSize: '13px',
    fontWeight: '500',
    marginBottom: '16px',
  },
  changePwSubmitBtn: {
    flex: 2,
    padding: '11px',
    backgroundColor: '#2563eb',
    color: '#ffffff',
    border: 'none',
    borderRadius: '9px',
    fontSize: '13px',
    fontWeight: '600',
    transition: 'all 0.15s',
  },
  confirmModal: {
    backgroundColor: '#ffffff',
    borderRadius: '16px',
    padding: '32px 28px',
    width: '350px',
    maxWidth: '92vw',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
  },
  confirmIconWrap: {
    width: '52px',
    height: '52px',
    borderRadius: '14px',
    backgroundColor: '#fef2f2',
    border: '1px solid #fecaca',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '16px',
  },
  switchIconWrap: {
    width: '52px',
    height: '52px',
    borderRadius: '14px',
    backgroundColor: '#eff6ff',
    border: '1px solid #bfdbfe',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '16px',
  },
  confirmCancelBtn: {
    flex: 1,
    padding: '10px',
    backgroundColor: '#f1f5f9',
    color: '#475569',
    border: '1px solid #e2e8f0',
    borderRadius: '9px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.15s',
  },
  confirmLogoutBtn: {
    flex: 1,
    padding: '10px',
    backgroundColor: '#ef4444',
    color: '#ffffff',
    border: 'none',
    borderRadius: '9px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    transition: 'all 0.15s',
  },
  switchConfirmBtn: {
    flex: 1,
    padding: '10px',
    backgroundColor: '#2563eb',
    color: '#ffffff',
    border: 'none',
    borderRadius: '9px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    transition: 'all 0.15s',
  },
};

export default S;
