const styles = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0b1329',
    backgroundImage: `
      radial-gradient(circle at 20% 25%, rgba(249, 115, 22, 0.12) 0%, transparent 45%),
      radial-gradient(circle at 80% 75%, rgba(37, 99, 235, 0.15) 0%, transparent 50%),
      linear-gradient(180deg, #0b1329 0%, #070d1e 100%)
    `,
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    padding: '32px 16px',
    boxSizing: 'border-box',
    position: 'relative',
  },
  cardWrapper: {
    width: '100%',
    maxWidth: '440px',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    zIndex: 1,
  },
  brandSection: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    gap: '12px',
    marginBottom: '4px',
  },
  brandLogoWrap: {
    width: '54px',
    height: '54px',
    borderRadius: '14px',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    border: '1px solid rgba(255, 255, 255, 0.14)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 8px 24px -4px rgba(0, 0, 0, 0.4)',
    backdropFilter: 'blur(8px)',
  },
  brandLogoImg: {
    width: '36px',
    height: '36px',
    objectFit: 'contain',
  },
  brandLogoFallback: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    backgroundColor: 'rgba(249, 115, 22, 0.15)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandTitle: {
    fontSize: '20px',
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: '0.8px',
    margin: 0,
    lineHeight: '1.2',
  },
  brandSubtitle: {
    fontSize: '10px',
    fontWeight: '600',
    color: '#94a3b8',
    letterSpacing: '0.6px',
    margin: 0,
    textTransform: 'uppercase',
  },
  card: {
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: '20px',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.35), 0 0 0 1px rgba(255, 255, 255, 0.08)',
    padding: '36px 32px',
    boxSizing: 'border-box',
    border: '1px solid #e2e8f0',
  },
  header: {
    marginBottom: '24px',
    textAlign: 'center',
  },
  title: {
    margin: '0 0 6px 0',
    fontSize: '24px',
    fontWeight: '700',
    color: '#0f172a',
    letterSpacing: '-0.4px',
  },
  subtitle: {
    margin: 0,
    fontSize: '13px',
    color: '#64748b',
    lineHeight: '1.5',
  },
  errorBox: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '20px',
    padding: '12px 14px',
    backgroundColor: '#fef2f2',
    border: '1px solid #fecaca',
    color: '#dc2626',
    borderRadius: '10px',
    fontSize: '13px',
    fontWeight: '500',
    lineHeight: '1.4',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  label: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#334155',
  },
  inputWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    width: '100%',
  },
  inputIcon: {
    position: 'absolute',
    left: '14px',
    color: '#94a3b8',
    pointerEvents: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    width: '100%',
    padding: '11px 40px 11px 42px',
    fontSize: '14px',
    borderRadius: '10px',
    border: '1px solid #cbd5e1',
    outline: 'none',
    boxSizing: 'border-box',
    color: '#0f172a',
    backgroundColor: '#f8fafc',
    transition: 'all 0.2s ease',
  },
  inputNoRight: {
    width: '100%',
    padding: '11px 14px 11px 42px',
    fontSize: '14px',
    borderRadius: '10px',
    border: '1px solid #cbd5e1',
    outline: 'none',
    boxSizing: 'border-box',
    color: '#0f172a',
    backgroundColor: '#f8fafc',
    transition: 'all 0.2s ease',
  },
  togglePasswordBtn: {
    position: 'absolute',
    right: '10px',
    background: 'none',
    border: 'none',
    color: '#94a3b8',
    cursor: 'pointer',
    padding: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '6px',
    transition: 'color 0.15s ease',
  },
  button: {
    width: '100%',
    padding: '12px 16px',
    marginTop: '6px',
    fontSize: '15px',
    fontWeight: '600',
    color: '#ffffff',
    backgroundColor: '#2563eb',
    border: 'none',
    borderRadius: '10px',
    boxShadow: '0 4px 12px rgba(37, 99, 235, 0.28)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    transition: 'all 0.2s ease',
  },
  footer: {
    marginTop: '22px',
    textAlign: 'center',
    fontSize: '13px',
  },
  link: {
    color: '#2563eb',
    fontWeight: '600',
    textDecoration: 'none',
  },
  systemFooter: {
    textAlign: 'center',
    fontSize: '12px',
    color: '#64748b',
    letterSpacing: '0.2px',
  },
};

export default styles;