const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: '28px',
    maxWidth: '1200px',
    margin: '0 auto',
    paddingBottom: '40px',
  },

  heroCard: {
    position: 'relative',
    backgroundColor: '#0b1329',
    borderRadius: '16px',
    padding: '48px 40px',
    overflow: 'hidden',
    boxShadow: '0 10px 30px -5px rgba(11, 19, 41, 0.4)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
  },
  heroBackgroundEffect: {
    position: 'absolute',
    top: '-50%',
    right: '-20%',
    width: '600px',
    height: '600px',
    background: 'radial-gradient(circle, rgba(88, 101, 242, 0.25) 0%, rgba(220, 38, 38, 0.15) 50%, transparent 70%)',
    pointerEvents: 'none',
  },
  heroContent: {
    position: 'relative',
    zIndex: 1,
    maxWidth: '720px',
  },
  badgeRow: {
    marginBottom: '16px',
  },
  heroBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    border: '1px solid rgba(255, 255, 255, 0.15)',
    padding: '6px 14px',
    borderRadius: '9999px',
    fontSize: '11px',
    fontWeight: '700',
    color: '#e2e8f0',
    letterSpacing: '0.8px',
  },
  heroTitle: {
    margin: '0 0 16px 0',
    fontSize: '32px',
    fontWeight: '800',
    color: '#ffffff',
    lineHeight: '1.25',
    letterSpacing: '-0.5px',
  },
  discordGradientText: {
    background: 'linear-gradient(135deg, #5865F2 0%, #a855f7 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  heroSubtitle: {
    margin: '0 0 28px 0',
    fontSize: '15px',
    color: '#94a3b8',
    lineHeight: '1.7',
  },
  heroActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    flexWrap: 'wrap',
  },
  primaryJoinBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '10px',
    backgroundColor: '#5865F2',
    color: '#ffffff',
    padding: '12px 24px',
    borderRadius: '10px',
    fontWeight: '600',
    fontSize: '14px',
    textDecoration: 'none',
    boxShadow: '0 4px 14px rgba(88, 101, 242, 0.4)',
    transition: 'all 0.2s ease',
  },
  secondaryCopyBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    color: '#f8fafc',
    border: '1px solid rgba(255, 255, 255, 0.16)',
    padding: '12px 20px',
    borderRadius: '10px',
    fontWeight: '600',
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },

  previewSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  sectionHeader: {
    paddingLeft: '4px',
  },
  sectionTitle: {
    margin: '0 0 4px 0',
    fontSize: '20px',
    fontWeight: '700',
    color: '#0f172a',
  },
  sectionSubtitle: {
    margin: 0,
    fontSize: '14px',
    color: '#64748b',
  },
  discordMockupCard: {
    backgroundColor: '#313338',
    borderRadius: '14px',
    border: '1px solid #3f4147',
    overflow: 'hidden',
    boxShadow: '0 8px 24px -4px rgba(0, 0, 0, 0.2)',
  },
  mockupHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#2b2d31',
    padding: '14px 20px',
    borderBottom: '1px solid #232428',
  },
  mockupChannelName: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '15px',
  },
  mockupStatusPill: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    color: '#22c55e',
    backgroundColor: 'rgba(34, 197, 94, 0.12)',
    padding: '4px 10px',
    borderRadius: '9999px',
    fontWeight: '600',
  },
  mockupStatusDot: {
    width: '7px',
    height: '7px',
    borderRadius: '50%',
    backgroundColor: '#22c55e',
  },
  mockupBody: {
    display: 'flex',
    gap: '16px',
    padding: '24px 20px',
  },
  mockupAvatar: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    backgroundColor: '#ef4444',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  mockupMessageContent: {
    flex: 1,
    minWidth: 0,
  },
  mockupAuthorRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '8px',
  },
  mockupAuthorName: {
    fontWeight: '600',
    color: '#ffffff',
    fontSize: '15px',
  },
  mockupBotTag: {
    backgroundColor: '#5865F2',
    color: '#ffffff',
    fontSize: '10px',
    fontWeight: '700',
    padding: '2px 5px',
    borderRadius: '4px',
  },
  mockupTimestamp: {
    fontSize: '12px',
    color: '#949ba4',
  },
  mockupEmbed: {
    position: 'relative',
    backgroundColor: '#2b2d31',
    borderRadius: '6px',
    overflow: 'hidden',
    maxWidth: '560px',
    marginTop: '6px',
  },
  embedBorderHighlight: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: '4px',
    backgroundColor: '#ef4444',
  },
  embedInner: {
    padding: '16px 18px 16px 22px',
  },
  embedTitle: {
    fontWeight: '700',
    fontSize: '15px',
    color: '#ffffff',
    marginBottom: '6px',
  },
  embedDescription: {
    fontSize: '13px',
    color: '#dbdee1',
    lineHeight: '1.5',
    marginBottom: '14px',
  },
  embedFieldsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '12px',
    marginBottom: '14px',
  },
  embedField: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  embedFieldKey: {
    fontSize: '11px',
    fontWeight: '600',
    color: '#949ba4',
    textTransform: 'uppercase',
  },
  embedFieldValue: {
    fontSize: '13px',
    color: '#f2f3f5',
  },
  embedFieldValueMono: {
    fontSize: '12px',
    fontFamily: 'monospace',
    color: '#e2e8f0',
    backgroundColor: '#1e1f22',
    padding: '2px 6px',
    borderRadius: '4px',
    display: 'inline-block',
    width: 'fit-content',
  },
  embedFieldValueLink: {
    fontSize: '13px',
    color: '#00a8fc',
    textDecoration: 'underline',
    cursor: 'pointer',
  },
  embedFooter: {
    fontSize: '11px',
    color: '#949ba4',
    borderTop: '1px solid #383a40',
    paddingTop: '8px',
    marginTop: '4px',
  },

  featuresGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '18px',
  },
  featureCard: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    padding: '24px 20px',
    border: '1px solid #e2e8f0',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.05)',
  },
  featureIconWrap: {
    width: '44px',
    height: '44px',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '14px',
  },
  featureTitle: {
    margin: '0 0 8px 0',
    fontSize: '16px',
    fontWeight: '700',
    color: '#0f172a',
  },
  featureDesc: {
    margin: 0,
    fontSize: '13px',
    color: '#64748b',
    lineHeight: '1.6',
  },

  infoSplitGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(340px, 1fr))',
    gap: '20px',
  },
  infoCard: {
    backgroundColor: '#ffffff',
    borderRadius: '14px',
    padding: '24px',
    border: '1px solid #e2e8f0',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.05)',
  },
  infoCardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '20px',
    paddingBottom: '12px',
    borderBottom: '1px solid #f1f5f9',
  },
  infoCardTitle: {
    margin: 0,
    fontSize: '16px',
    fontWeight: '700',
    color: '#0f172a',
  },
  stepList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  stepItem: {
    display: 'flex',
    gap: '14px',
    alignItems: 'flex-start',
  },
  stepNumber: {
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    backgroundColor: '#eff6ff',
    color: '#2563eb',
    fontSize: '13px',
    fontWeight: '700',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    border: '1px solid #bfdbfe',
  },
  stepTitle: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#1e293b',
    marginBottom: '2px',
  },
  stepDesc: {
    fontSize: '12px',
    color: '#64748b',
    lineHeight: '1.5',
  },
  channelList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  channelItem: {
    padding: '10px 12px',
    borderRadius: '8px',
    backgroundColor: '#f8fafc',
    border: '1px solid #f1f5f9',
  },
  channelBadgeRed: {
    fontSize: '13px',
    fontWeight: '700',
    color: '#dc2626',
    marginBottom: '4px',
  },
  channelBadgeAmber: {
    fontSize: '13px',
    fontWeight: '700',
    color: '#d97706',
    marginBottom: '4px',
  },
  channelBadgeBlue: {
    fontSize: '13px',
    fontWeight: '700',
    color: '#2563eb',
    marginBottom: '4px',
  },
  channelBadgeSlate: {
    fontSize: '13px',
    fontWeight: '700',
    color: '#475569',
    marginBottom: '4px',
  },
  channelDesc: {
    fontSize: '12px',
    color: '#64748b',
    lineHeight: '1.4',
  },
};

export default styles;
